<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DS-005056C00008" name="com.digi.selenium.app.Stores_Orders.Store_Orders_Prepaid" tests="1" failures="0" timestamp="10 Sep 2015 11:13:22 GMT" time="0.001" errors="1">
  <testcase name="validateStoreNordersTrackDeliveryLink" time="0.001" classname="com.digi.selenium.app.Stores_Orders.Store_Orders_Prepaid">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.digi.selenium.util.common.PageNavigation.handleClearInputField_ByName(PageNavigation.java:794)
	at com.digi.selenium.util.common.PageNavigation.signInWithMSSIDN_stage(PageNavigation.java:951)
	at com.digi.selenium.util.Stores_Orders.Stores_Orders_Prepaid_Util.setUp(Stores_Orders_Prepaid_Util.java:43)
	at com.digi.selenium.app.Stores_Orders.Store_Orders_Prepaid.initDriver(Store_Orders_Prepaid.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- validateStoreNordersTrackDeliveryLink -->
</testsuite> <!-- com.digi.selenium.app.Stores_Orders.Store_Orders_Prepaid -->
